### ISSUE TITLE
example.demo.test

### ISSUE THREAD

**Issue by carlofraue79** [ofeige/symfony-demo-vagrant#2]
I have download and execute the step such as indicated in installation guide at the moment to point http://example.demo.test/ i obtaind connection found.
I have also try to locate composer.json and i haven't found 
I have also try to search the configuration of site in subject,but there aren't any configuration. 
Can you clarify?

**Comment by ofeige** [comment]
Yes, I can clarify that. I'm sorry for the inconvenience.  There is a config.yml in the root folder https://github.com/ofeige/symfony-demo-vagrant/blob/master/config.yaml

the server name is configured as "servername" and below you can define one or more symfony projects. Standard is ui and api. The complete name is ui.demo.test and api.demo.test. API and UI are two other projects in my Github Repo. 
https://github.com/ofeige/symfony-demo-ui and 
https://github.com/ofeige/symfony-demo-api. There you can find the installation instruction: https://github.com/ofeige/symfony-demo-ui/blob/master/README.md

If you a looking for the not customized version, you will find that here https://github.com/ofeige/vagrant-debian-ansible-lemp

I hope that helps.

**Comment by carlofraue79** [comment]
Before you response me i have located the ui.demo.test under sites-enabled of nginx.
Many thanks to clarify the point,with your package i can resolve my problem with yarn and vagrant.
